### ISSUE TITLE
Test failing for Valid and Invalid Receiver

### ISSUE THREAD

**Issue by Ectsang** [AnAllergyToAnalogy/ERC721#2]
https://github.com/AnAllergyToAnalogy/ERC721/blob/76039063f2e1181ace9364283213ff714af6dd70/tests/Token.test.js#L11

I was following the steps from: https://medium.com/coinmonks/jumping-into-solidity-the-erc721-standard-part-5-3b91f39fc1ee 

And got:
1) Token Contract
       Can safeTransferFrom your own coin to valid contract:
     TypeError: Cannot read property 'send' of null
      at Context.it (test/Token.test.js:99:13)

```
it('Can safeTransferFrom your own coin to valid contract', async () => {
        const tokenId = 1;
        const owner = accounts[0];
        let gotReceiver;


        const receiver = await new web3.eth.Contract(JSON.parse(compiledValidReceiver.interface))
            .deploy({
                data: compiledValidReceiver.bytecode
            })
            .send({from: accounts[0], gas:'1000000'});                   // <-- line 99
```

Is it a problem with the contract not deploying? Any hints on how to fix it?

Thanks!

**Comment by AnAllergyToAnalogy** [comment]
You need to write and compile Valid and Invalid Receiver contracts, which were defined in [part 2](https://medium.com/coinmonks/jumping-into-solidity-the-erc721-standard-part-2-383438734de5)
