### ISSUE TITLE
Is this line missing a bracket?

### ISSUE THREAD

**Issue by jiaolinfeng** [AnAllergyToAnalogy/ERC721#3]
https://github.com/AnAllergyToAnalogy/ERC721/blob/b8651ebbcba8d2ab4b1217d5fd4b846f80ed3704/TokenERC721.sol#L38
I think this line should be 
> bytes4(keccak256("safeTransferFrom(address,address,uint256)"))

Excuse me for any possible offence.

**Comment by AnAllergyToAnalogy** [comment]
Yes, you are completely correct. Thank you for pointing this out! I've made that fix.
